### ISSUE TITLE
Problems with separate folder for mocks

### ISSUE THREAD

**Issue by subtle-byte** [subtle-byte/mockigo#10]
I discovered few problems with placing mocks in separate folder:

* Import cycles are probable.
E.g. if we have the code:
```go
package pkg

type A int
type B interface { Foo(A) } // Foo receives A, so the mock will import the current package to get A
```
and if we have the mock in separate package, then it will be impossible to import the mock in file e.g. `my_test.go` with `package pkg` - we will be forced to use `package pkg_test`.
* `go test` counts the code code coverage for these mocks, obviously mocks have no tests, so total test coverage of the project will decrease.

Probable solution: Go away from single folder for all mocks, and place the mocks beside the interfaces - i.e. in the same package.

**Comment by aselus-hub** [comment]
I have a fork where I redid input w/ kong and have this feature as an option including post/prefix support, want me to submit a pull request? will save you this work

**Comment by subtle-byte** [comment]
Fixed with https://github.com/subtle-byte/mockigo/pull/13
