### ISSUE TITLE
Panic when `root-dir` is '.'

### ISSUE THREAD

**Issue by shackra** [subtle-byte/mockigo#12]
I'm trying to use mocking with a project I have, I don't use a cleaner project structure for this one, so all the files exists on the root of the project. When configuring mockigo and trying to run it, it panics:

```
$ mockigo
panic: map[string]generator.Interfaces{} "/home/jorge/code/goimapnotify"

goroutine 1 [running]:
github.com/subtle-byte/mockigo/internal/generator.Generate({0xc000024480, 0x1d}, 0xc000094f30, {0xc00001e420, 0x23})
	/home/jorge/go/pkg/mod/github.com/subtle-byte/mockigo@v0.0.0-20230401025602-15559d0ca335/internal/generator/generator.go:60 +0x6b4
main.runMockigo({0x816db0?, 0x633fe0?}, {0xc000028d50, 0x5}, {0xc000080360, 0x2, 0x2})
	/home/jorge/go/pkg/mod/github.com/subtle-byte/mockigo@v0.0.0-20230401025602-15559d0ca335/cmd/mockigo/main.go:43 +0x22c
main.main()
	/home/jorge/go/pkg/mod/github.com/subtle-byte/mockigo@v0.0.0-20230401025602-15559d0ca335/cmd/mockigo/main.go:83 +0x5fd
```

here is the `mockigo.yaml`:

```yaml
root-dir: "."
mocks-dir: mocks
walk:
  - "!."
  - "idleClient"
```

**Comment by elzorrorebelde** [comment]
if you leave `root-dir` empty, it defaults to `$(pwd)/internal`:

```
$ mockigo
ERROR: read dir: open /home/jorge/code/goimapnotify/internal: no such file or directory
ERROR: generate: load packages: err: chdir /home/jorge/code/goimapnotify/internal: no such file or directory: stderr:
```

**Comment by elzorrorebelde** [comment]
any idea?

```
    66:				log.Printf("ERROR: get rel path of package dir %s in root dir: %v\n", pkgDir, err)
    67:				continue
    68:			}
    69:			mockDir := filepath.Join(mocksDir, inRoot)
    70:			interfacesSelector, ok := pkgDirs[pkgDir]
=>  71:			if !ok {
    72:				panic(fmt.Sprintf("%#v %q", pkgDirs, pkgDir))
    73:			}
    74:			err = generateForPackage(pkg.Types, mockDir, interfacesSelector)
    75:			if err != nil {
    76:				log.Printf("ERROR: generate for package %s: %v\n", pkg.PkgPath, err)
(dlv) locals
pkgs = []*golang.org/x/tools/go/packages.Package len: 1, cap: 1, [...]
(err) = error nil
realRootDirPath = "/home/jorge/code/mockigo/internal/generator"
pkg = ("*golang.org/x/tools/go/packages.Package")(0xc0004b5080)
goFiles = []string len: 2, cap: 2, [...]
pkgDir = "/home/jorge/code/mockigo/internal/generator"
err = error nil
inRoot = "."
mockDir = "/home/jorge/code/mockigo/internal/generator/mocks"
interfacesSelector = github.com/subtle-byte/mockigo/internal/generator.Interfaces {IncludeInterfaces: false, InterfacesExceptions: map[string]struct {} nil}
ok = false
(dlv)
```

**Comment by subtle-byte** [comment]
Thanks for reporting, currently I'm working on different approach to solve the issues described here (https://github.com/subtle-byte/mockigo/issues/10).
Probably you could try this new version: https://github.com/subtle-byte/mockigo/pull/13
You can install the version from PR using: `go install github.com/subtle-byte/mockigo/cmd/mockigo@mocks-beside`
The readme is here: [README.md](https://github.com/subtle-byte/mockigo/blob/6af8cea080283abe80e30fa812875c580f538d35/README.md)

**Comment by elzorrorebelde** [comment]
I noticed that no interface is picked, regardless the existence of Go files with interfaces in the same place `mockigo.yaml` exists, did you notice that? I highlight this because this is triggering the call to `panic` at line 72 in my debugging.

**Comment by elzorrorebelde** [comment]
> Thanks for reporting, currently I'm working on different approach to solve the issues described here (#10). Probably you could try this new version: #13 You can install the version from PR using: `go install github.com/subtle-byte/mockigo/cmd/mockigo@mocks-beside` The readme is here: [README.md](https://github.com/subtle-byte/mockigo/blob/6af8cea080283abe80e30fa812875c580f538d35/README.md)

I gave it a run and no panics, so far, if you set `- "!."`

**Comment by elzorrorebelde** [comment]
any news with `mocks-beside` branch?

**Comment by subtle-byte** [comment]
Merged just now
