### ISSUE TITLE
Can we have Mock prefix for mock constructor functions

### ISSUE THREAD

**Issue by iesen** [subtle-byte/mockigo#2]
For example for a **FooInterface**
```
type FooService interface {
   ...
}

type fooService struct {
   ...somedeps...
}

func NewFooService(...somedeps..) {
    return &fooService{...somedeps...)
}
```

generated mock file contains a constructor like below
```
type FooService struct {
    mock *mock.Mock
}

func NewFooService(t mock.Testing) *FooService {
    t.Helper()
    return &CatalogServiceOperationsService{mock: mock.NewMock(t)}
}
```
Can mock constructor function be generated like **func NewMockFooService(t mock.Testing)** ?

it may be confusing if we have already have a constructor function with same name in the package where the interface exists.

**Comment by subtle-byte** [comment]
Hi.
> it may be confusing if we have already have a constructor function with same name in the package where the interface exists.

It is supposed that mockigo will create mocks in a separate folder, so there will not be a conflict with the existing constructor. Also during the usage of the mock, it is obvious that we use the constructor of the mock, see the example from readme:
```go
import service_mocks "github.com/someuser/somerepo/internal/mocks/service"
...
fooBar := service_mocks.NewFooBar(t)
```

**Comment by subtle-byte** [comment]
Fixed with https://github.com/subtle-byte/mockigo/pull/13
