### ISSUE TITLE
Incorrect mock generated for files that have imports with last path part containing dash character

### ISSUE THREAD

**Issue by iesen** [subtle-byte/mockigo#3]
On interface package if we have an import with last path part with dashes:

```
import (
    "github.com/xanzy/go-gitlab"
)
```

incorrectly generated mock
```
import go-gitlab "github.com/xanzy/go-gitlab"
...

var _r0 []*go-gitlab.Project

```
go-gitlab.Project does not compile here as usual.

We can drop dashes and create import prefix like **gogitlab** for this case.

**Comment by subtle-byte** [comment]
Thanks for the bug report, seems like it is fixed now, you are welcome to reopen the issue if you still have this problem
