### ISSUE TITLE
Unexpected package creation during export data loading

### ISSUE THREAD

**Issue by iesen** [subtle-byte/mockigo#7]
Running mockigo inside official golang alpine based inside produces following error:
```
Unexpected package creation during export data loading
```

after some googling it is caused by **golang.org/x/tools** package and related to generics.
It is [fixed](https://github.com/golang/go/issues/51629) in version v0.1.12

i created #6 for updating x/tools dependency.

**Comment by subtle-byte** [comment]
Thanks for the bug report and PR, seems like it is fixed now, you are welcome to reopen the issue if you still have this problem
